### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by djperrefort**
This pull request brings the package to a stable, 1.0 release. Updates include added functionality to combined tables (Vizier table parsing, and string Ids), improved documentation, and more extensive tests.

### CODE REVIEW

**Comment by djperrefort** [comment]
@troyraen Can you please look over the Getting Started section of the docs at https://sn-data.readthedocs.io/en/1.0.0/

**Comment by troyraen** [comment]
Tried to do this tonight, but received the following error when trying to do `dr3.download_module_data()`:

`HTTPError: 500 Server Error: Internal Server Error for url: http://cdsarc.u-strasbg.fr/viz-bin/nph-Cat/tar.gz?J/AJ/154/211`

It looks like the CDS archives are actually down. I can get to VizieR, but not anything starting with `cdsarc.u-strasbg.fr`. I'll try again tomorrow.

**Comment by troyraen** [comment]
On the Slow Start page under Accessing Data: first code block, line 6

I believe it's missing a `dr3.`, and the full line should be `data_table = dr3.get_data_for_id(demo_id)`

**Comment by troyraen** [comment]
@djperrefort I'm now looking at the actual data and running code on the getting started pages (mostly for my own benefit/experience, I know you already merged this in). 

I noticed you have a couple of lines of code on [this page](https://sn-data.readthedocs.io/en/latest/getting_started/slow_start.html) that call `data_table.meta['redshift']`, but I don't think the `redshift` key exists in these dicts. I think it should be `data_table.meta['z']`

**Comment by djperrefort** [comment]
Oh that’s a good catch. I switched the key name a few months ago. @troyraen I’ll fix that today.

**Pull request merged**
